all:
  hosts:
    local_opensearch:
      ansible_host: host.containers.internal
      ansible_port: 9200
      api_username: admin
      api_password: myStrongPassword123!
      api_verify_certs: false
