all:
  hosts:
    local_opensearch:
      ansible_host: host.containers.internal
      ansible_network_os: castorsky.opensearch.opensearch
      ansible_connection: httpapi
      ansible_httpapi_port: 9200
      ansible_httpapi_use_ssl: true
      ansible_httpapi_validate_certs: false
      ansible_user: admin
      ansible_httpapi_pass: myStrongPassword123!
#      ansible_user: "{{ lookup('env', 'OPENSEARCH_API_USERNAME') }}"
#      ansible_httpapi_pass: "{{ lookup('env', 'OPENSEARCH_API_PASSWORD') }}"

