- name: Devel opensearch module
  hosts: local_opensearch
  gather_facts: false
  tasks:
    - name: Test index
      castorsky.opensearch.opensearch_index:
        name: "checker-index"
        settings:
#          number_of_shards: 2
          number_of_replicas: 0
        state: present
      register: checker_index

#    - name: Test tenant
#      castorsky.opensearch.opensearch_tenant:
#        name: "checker-tenant"
#        description: "Tenant for Checker"
#        state: present
#      register: checker_tenant

#    - name: Test user
#      castorsky.opensearch.opensearch_user:
#        name: "checker-user"
#        password: "#v3DWeSVDtD2~eqm1"
#        description: "Checker User"
#        opendistro_security_roles:
#          - all_access
#        attributes:
#          shell: "/bin/tcsh"
#          home: "/home/checker"
#        state: present
#      register: checker_user
#
#    - name: Test role
#      castorsky.opensearch.opensearch_role:
#        name: "role-checker"
#        description: "Role for Checker1"
#        cluster_permissions:
#          - "cluster_composite_ops"
#          - "indices_monitor"
#        state: present
#      register: checker_role
#
#    - name: Test rolemapping
#      castorsky.opensearch.opensearch_role_mapping:
#        name: "role-checker"
#        description: "Role Mapping for role 'role-checker'"
#        users: ["checker-user", "kibana"]
#        state: present
#      register: checker_rolemap

# #    - name: Save
# #      ansible.builtin.copy:
# #        content: "{{ checker }}"
# #        dest: "debug.json"
# #        owner: "castor"

    - name: Debug
      ansible.builtin.debug:
        var: "{{ item }}"
      loop:
        - checker_index
#        - checker_role
#        - checker_rolemap
#        - checker_tenant
#        - checker_user
