- name: Devel opensearch module
  hosts: localhost
  gather_facts: False
  tasks:
    - name: Test
      castorsky.opensearch.opensearch_tenant:
        name: "checker-tenant"
        description: "Tenant for Checker"
        state: present
      register: checker

    - name: Test2
      castorsky.opensearch.opensearch_role:
        name: "role-checker"
        description: "Role for Checker"
        cluster_permissions:
          - "cluster_composite_ops"
          - "indices_monitor"
        state: absent
      register: checker

#    - name: Save
#      ansible.builtin.copy:
#        content: "{{ checker }}"
#        dest: "debug.json"
#        owner: "castor"

    - name: Debug
      ansible.builtin.debug:
        var: checker
